"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
// This file is auto-generated from src/index.ts
// Do not edit this file directly.
const_require = require("firebase-functions/lib/common/providers/https");
const index_1 = require("./index");
exports.setAdminRole = index_1.setAdminRole;
exports.createUserWithRole = index_1.createUserWithRole;
exports.processDocument = index_1.processDocument;
